openapi: 3.0.1
info:
  title: Swagger ToBuyApp API
  description: This is the ToBuyApp server.
  termsOfService: http://swagger.io/terms/
  contact:
    name: API Support
    url: http://www.swagger.io/support
    email: support@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
- url: /api/v1
paths:
  /items:
    get:
      tags:
      - fetchAllItems
      summary: Fetch all items
      description: Fetch all items
      operationId: itemsGET
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.AllItemsResponse'
        "404":
          description: ""
          content: {}
        "500":
          description: ""
          content: {}
      security:
      - JWT: []
      x-swagger-router-controller: FetchAllItems
    post:
      tags:
      - createItem
      summary: Create item
      description: Create user's item
      operationId: itemsPOST
      requestBody:
        description: Create Item Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.MutationItemRequest'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.ItemResponse'
        "400":
          description: ""
          content: {}
        "500":
          description: ""
          content: {}
      security:
      - JWT: []
      x-codegen-request-body-name: requestBody
      x-swagger-router-controller: CreateItem
  /items/{id}:
    get:
      tags:
      - fetchItemBuyId
      summary: Fetch item by id
      description: Fetch user's item by id
      operationId: itemsIdGET
      parameters:
      - name: id
        in: path
        description: Item ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.ItemResponse'
        "404":
          description: ""
          content: {}
        "500":
          description: ""
          content: {}
      security:
      - JWT: []
      x-swagger-router-controller: FetchItemBuyId
  /items/{id}/delete:
    post:
      tags:
      - deleteItem
      summary: Delete item
      description: Delete user's item
      operationId: itemsIdDeletePOST
      parameters:
      - name: id
        in: path
        description: Item ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: ""
          content: {}
        "400":
          description: ""
          content: {}
        "500":
          description: ""
          content: {}
      security:
      - JWT: []
      x-swagger-router-controller: DeleteItem
  /items/{id}/update:
    post:
      tags:
      - updateItem
      summary: Update item
      description: Update user's item
      operationId: itemsIdUpdatePOST
      parameters:
      - name: id
        in: path
        description: Item ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        description: Update Item Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.MutationItemRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.ItemResponse'
        "400":
          description: ""
          content: {}
        "500":
          description: ""
          content: {}
      security:
      - JWT: []
      x-codegen-request-body-name: requestBody
      x-swagger-router-controller: UpdateItem
  /me/delete:
    post:
      tags:
      - deleteUser
      summary: Delete User
      description: Delete User
      operationId: meDeletePOST
      requestBody:
        description: Delete User Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.DeleteUserRequest'
        required: true
      responses:
        "204":
          description: ""
          content: {}
        "400":
          description: ""
          content: {}
        "500":
          description: ""
          content: {}
      security:
      - JWT: []
      x-codegen-request-body-name: requestBody
      x-swagger-router-controller: DeleteUser
  /me/update:
    post:
      tags:
      - updateUser
      summary: Update User
      description: Update user's information
      operationId: meUpdatePOST
      requestBody:
        description: Update User Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.UpdateUserRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.UserResponse'
        "400":
          description: ""
          content: {}
        "500":
          description: ""
          content: {}
      security:
      - JWT: []
      x-codegen-request-body-name: requestBody
      x-swagger-router-controller: UpdateUser
  /me/update/password:
    post:
      tags:
      - updatePassword
      summary: Update Password
      description: Update user's password
      operationId: meUpdatePasswordPOST
      requestBody:
        description: Update User's Password Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.UpdatePasswordRequest'
        required: true
      responses:
        "200":
          description: ""
          content: {}
        "400":
          description: ""
          content: {}
        "500":
          description: ""
          content: {}
      security:
      - JWT: []
      x-codegen-request-body-name: requestBody
      x-swagger-router-controller: UpdatePassword
  /signin:
    post:
      tags:
      - signIn
      summary: SignIn
      description: SignIn
      operationId: signinPOST
      requestBody:
        description: SignIn Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.SignInRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.AuthResponse'
        "400":
          description: ""
          content: {}
        "401":
          description: ""
          content: {}
        "404":
          description: ""
          content: {}
        "500":
          description: ""
          content: {}
      x-codegen-request-body-name: requestBody
      x-swagger-router-controller: SignIn
  /signup:
    post:
      tags:
      - signUp
      summary: SignUp
      description: SignUp
      operationId: signupPOST
      requestBody:
        description: SignUp Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.SignUpRequest'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.AuthResponse'
        "400":
          description: ""
          content: {}
        "401":
          description: ""
          content: {}
        "404":
          description: ""
          content: {}
        "500":
          description: ""
          content: {}
      x-codegen-request-body-name: requestBody
      x-swagger-router-controller: SignUp
components:
  schemas:
    models.AllItemsResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/models.BaseItemResponse'
      example:
        items:
        - number: 1
          category_id: 1
          updated_at: 2022-05-01T17:23:17.494039+09:00
          name: test item
          created_at: 2022-05-01T17:23:17.494039+09:00
          description: This is a test item
          counter: 数
          id: 1
          deleted_at: ""
          status: 0
        - number: 1
          category_id: 1
          updated_at: 2022-05-01T17:23:17.494039+09:00
          name: test item
          created_at: 2022-05-01T17:23:17.494039+09:00
          description: This is a test item
          counter: 数
          id: 1
          deleted_at: ""
          status: 0
    models.AuthResponse:
      type: object
      properties:
        token:
          type: string
          example: ajiji1j98a
        user:
          $ref: '#/components/schemas/models.BaseUserResponse'
      example:
        user:
          updated_at: 2022-05-01T17:23:17.494039+09:00
          name: test user
          created_at: 2022-05-01T17:23:17.494039+09:00
          id: 1
          deleted_at: ""
          email: test@example.com
        token: ajiji1j98a
    models.BaseItemResponse:
      type: object
      properties:
        category_id:
          type: integer
          example: 1
        counter:
          type: string
          example: 数
        created_at:
          type: string
          example: 2022-05-01T17:23:17.494039+09:00
        deleted_at:
          type: string
          example: ""
        description:
          type: string
          example: This is a test item
        id:
          type: integer
          example: 1
        name:
          type: string
          example: test item
        number:
          type: integer
          example: 1
        status:
          type: integer
          example: 0
        updated_at:
          type: string
          example: 2022-05-01T17:23:17.494039+09:00
      example:
        number: 1
        category_id: 1
        updated_at: 2022-05-01T17:23:17.494039+09:00
        name: test item
        created_at: 2022-05-01T17:23:17.494039+09:00
        description: This is a test item
        counter: 数
        id: 1
        deleted_at: ""
        status: 0
    models.BaseUserResponse:
      type: object
      properties:
        created_at:
          type: string
          example: 2022-05-01T17:23:17.494039+09:00
        deleted_at:
          type: string
          example: ""
        email:
          type: string
          example: test@example.com
        id:
          type: integer
          example: 1
        name:
          type: string
          example: test user
        updated_at:
          type: string
          example: 2022-05-01T17:23:17.494039+09:00
      example:
        updated_at: 2022-05-01T17:23:17.494039+09:00
        name: test user
        created_at: 2022-05-01T17:23:17.494039+09:00
        id: 1
        deleted_at: ""
        email: test@example.com
    models.DeleteUserRequest:
      type: object
      properties:
        password:
          type: string
          example: password
    models.ItemResponse:
      type: object
      properties:
        item:
          $ref: '#/components/schemas/models.BaseItemResponse'
      example:
        item:
          number: 1
          category_id: 1
          updated_at: 2022-05-01T17:23:17.494039+09:00
          name: test item
          created_at: 2022-05-01T17:23:17.494039+09:00
          description: This is a test item
          counter: 数
          id: 1
          deleted_at: ""
          status: 0
    models.MutationItemRequest:
      type: object
      properties:
        category_id:
          type: integer
          example: 1
        counter:
          type: string
          example: 個
        description:
          type: string
          example: This is a test item
        name:
          type: string
          example: test item
        number:
          type: integer
          example: 1
        status:
          type: integer
          example: 0
    models.SignInRequest:
      type: object
      properties:
        email:
          type: string
          example: test@example.com
        password:
          type: string
          example: password
    models.SignUpRequest:
      type: object
      properties:
        email:
          type: string
          example: test@example.com
        name:
          type: string
          example: test user
        password:
          type: string
          example: password
    models.UpdatePasswordRequest:
      type: object
      properties:
        new_password:
          type: string
          example: newPassword
        password:
          type: string
          example: password
    models.UpdateUserRequest:
      type: object
      properties:
        email:
          type: string
          example: test@example.com
        name:
          type: string
          example: test user
    models.UserResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/models.BaseUserResponse'
      example:
        user:
          updated_at: 2022-05-01T17:23:17.494039+09:00
          name: test user
          created_at: 2022-05-01T17:23:17.494039+09:00
          id: 1
          deleted_at: ""
          email: test@example.com
  securitySchemes:
    JWT:
      type: apiKey
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
